input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:account-multiple
    initial: false
  is_away:
    name: Away Mode
    icon: mdi:home

device_tracker:
  - platform: unifi
    host: !secret unifi_controller
    verify_ssl: false
    username: hass
    password: !secret unifi
    interval_seconds: 22 
    new_device_defaults:
      track_new_devices: True
      hide_if_away: True
    detection_time: 300
    ssid_filter:
      - "Test LAN - Please Ignore"
      - "Guest WiFi"

sensor:
  - platform: template
    sensors:
      guests:
        icon_template: mdi:account-multiple
        friendly_name: "Guests"
        value_template: >
          {%- for device in state_attr("group.all_devices", "entity_id") %}
          {%- if device not in ['device_tracker.stephensiphone', 'device_tracker.iphone'] and is_state(device, "home") %}
          {{ state_attr(device, "friendly_name") }}
          {%- endif %}
          {%- endfor %}
        entity_id: !include ../people.yaml

automation:
  # Home Boolean
  - alias: 'Set Away Mode'
    trigger:
      platform: state
      entity_id: group.all_devices
      to: 'not_home'
    # Do not set this if GUEST MODE is enabled
    condition:
      condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.is_away

  - alias: 'Set Home Mode'
    trigger:
      platform: state
      entity_id: group.all_devices
      to: 'home'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.is_away

  ##########
  #  AWAY  #
  ##########

  - alias: 'Notify When Away'
    trigger:
      platform: state
      entity_id: input_boolean.is_away
      to: 'on'
    action:
      service: notify.notify
      data_template:
        message: "Home set to away."

  - alias: 'Away Mode - Lock Doors'
    trigger:
      - platform: state
        entity_id: input_boolean.is_away
        to: 'on'
    action:
      service: lock.lock
      entity_id: group.all_locks

  - alias: 'Away Mode - Lights'
    trigger:
      platform: state
      entity_id: input_boolean.is_away
      to: 'on'
    action:
      service: light.turn_off
      entity_id: group.all_lights

  - alias: 'Away Mode - Switches'
    trigger:
      platform: state
      entity_id: input_boolean.is_away
      to: 'on'
    action:
      service: switch.turn_off
      entity_id: group.all_switches

  - alias: 'Away Mode - Nest'
    trigger:
      platform: state
      entity_id: input_boolean.is_away
      to: 'on'
    action:
      service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: true

  - alias: 'Away Mode - TV'
    trigger:
      platform: state
      entity_id: input_boolean.is_away
      to: 'on'
    action:
      service: rest_command.basement_tv_power_off
  
  - alias: 'Office When Stephen Not Home'
    trigger:
    - entity_id: device_tracker.stephensiphone
      platform: state
      from: 'home'
      to: 'not_home'
    condition: []
    action:
    - data:
        entity_id: light.office_floor_lamp
      service: light.turn_off

  ############
  #   HOME   #
  ############

  - alias: 'Home Mode - Unlock Upon Arrival'
    trigger:
      - platform: state
        entity_id: device_tracker.stephensiphone
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: device_tracker.iphone
        from: 'not_home'
        to: 'home'
    action:
      - service: lock.unlock
        entity_id: lock.schlage_be469_touchscreen_deadbolt_locked 
    condition:
      condition: state
      entity_id: lock.schlage_be469_touchscreen_deadbolt_locked
      state: 'locked'

  - alias: 'Notify When Home'
    trigger:
      platform: state
      entity_id: !include ../people.yaml 
      to: 'home'
    action:
      service_template: >
        {% if trigger.to_state.attributes.friendly_name == "Felipe" %}
          notify.ios_stephen
        {% elif trigger.to_state.attributes.friendly_name == "Stephen" %}
          notify.ios_iphone
        {% else %}
          notify.notify
        {% endif %}
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} is home!

  - alias: 'Home Mode - Nest'
    trigger:
      platform: state
      entity_id: input_boolean.is_away
      to: 'off'
    action:
      service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: false

  - alias: 'Home Mode - Lights'
    trigger:
      platform: state
      entity_id: !include ../people.yaml 
      to: 'home'
    condition:
      condition: sun
      after: sunset
      before_offset: "-01:00:00"
    action:
      - service: switch.turn_on 
        data:
          entity_id: switch.back_entry_sconces 
      - service: light.turn_on 
        data:
          entity_id: light.kitchen_main_lights
          brightness_pct: 25
      - service: light.turn_on 
        data:
          entity_id: light.front_door_light 
          brightness_pct: 50

