rest_command:
  living_room_tv_power_off:
    url: http://X.X.X.X:8060/keypress/PowerOff
    method: post
  living_room_tv_power_on:
    url: http://X.X.X.X:8060/keypress/PowerOn
    method: post

switch:
  - name: living_room_tv
    platform: wake_on_lan
    mac_address:
    host: X.X.X.X
    broadcast_address: X.X.X.X
    turn_off:
      service: rest_command.living_room_tv_power_off
