input_number:
  day_temperature:
    name: Day Temperature
    min: 60
    max: 74
    step: 1
    mode: slider
    icon: mdi:weather-sunny
  night_temperature:
    name: Night Temperature
    min: 60
    max: 74
    step: 1
    mode: slider
    icon: mdi:weather-night

automation:
  - alias: 'Set Day Temperature'
    trigger:
      platform: state
      entity_id: input_select.house_mode
      from: 'night'
      to: 'home'
    action:
      service: climate.set_temperature
      data_template:
        entity_id: climate.thermostat
        temperature: "{{ states('input_number.day_temperature') | float }}"

  - alias: 'Set Night Temperature'
    trigger:
      platform: state
      entity_id: input_select.house_mode
      from: 'home'
      to: 'night'
    action:
      service: climate.set_temperature
      data_template:
        entity_id: climate.thermostat
        temperature: "{{ states('input_number.night_temperature') | float }}"
