- alias: 'Set theme at startup'
  initial_state: 'on'
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data:
      name: midnight

- alias: Turn New York Off Automatically
  trigger:
  - entity_id: switch.new_york 
    platform: state
    from: 'off'
    to: 'on'
    for: 
      minutes: 30
  condition: []
  action:
  - data:
      entity_id: switch.new_york
    service: switch.turn_off

- alias: Porch Light - Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
  - data:
      entity_id:
        - switch.back_entry_sconces
    service: switch.turn_on

- alias: Front Door Light - Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
  - data:
      entity_id:
        - light.front_door_light
    service: light.turn_on

- alias: Lock Low Battery
  trigger:
    platform: state
    entity_id:
      - sensor.assa_abloy_unknown_type0004_idaa00_alarm_type
      - sensor.assa_abloy_unknown_type0004_idaa00_alarm_type_2
    to: "167"
  action:
    - service: persistent_notification.create
      data:
        message: "One of your door locks has indicated it's battery is low."
