# reset solar peak at midnight
- alias: "Reset Solar Max"
  trigger:
    platform: time
    hours: 0
    minutes: 0
    seconds: 0
  action:
    service: input_number.set_value
    data:
      entity_id: input_number.solar_max
      value: 0

# monitor the solar peak and keep track of it
- alias: 'Set Solar Max'
  trigger:
    platform: state
    entity_id: sensor.solar_live
  condition:
    - condition: template
      value_template: >
        {% if (states('sensor.solar_live') | float) > (states('input_number.solar_max') | float) %}
          true
        {% else %}
          false
        {% endif %}
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.solar_max
      value: "{{ states('sensor.solar_live') | float }}"
