homeassistant:
  name: Home 
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 70
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages

#logger:
#  default: debug

http:
  api_password: !secret http
  base_url: !secret url

automation: !include_dir_merge_list automations
cloud: !include cloud.yaml
config:
conversation:
discovery:
frontend:
  themes: !include themes.yaml
group: !include groups.yaml
history:
ios:

logbook:
recorder:
  exclude:
    domains:
      - input_number
      - zwave
  db_url: !secret db_url
script: !include scripts.yaml
shopping_list:
sun:
tts:
  - platform: google
updater:

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

lutron_caseta:
  host: !secret lutron_hub
  keyfile: /config/certs/caseta.key
  certfile: /config/certs/caseta.crt
  ca_certs: /config/certs/caseta-bridge.crt

switch:
  - platform: tplink
    host: IP 
  - platform: tplink
    host: IP 
  - platform: tplink
    host: IP 

camera:
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BOX
    name: Radar
  - platform: uvc
    nvr: IP 
    key: !secret unifi_video_key
    password: !secret unifi_camera

sensor:
  - platform: season

  - platform: uptime
    unit_of_measurement: minutes

scene:
  - name: Dinner
    entities:
      light.dining_room_main_lights:
        state: on
        brightness: 40
      light.kitchen_main_lights:
        state: on
        brightness: 30
      light.living_room_floor_lamp:
        state: off
  - name: Lights Out
    entities:
      group.all_lights:
        state: off
      group.all_switches:
        state: off
         
nissan_leaf:
    username: !secret nissan_username
    password: !secret nissan_password
    region: NNA 
    nissan_connect: true 
    update_interval: 30 
    update_interval_charging: 15 
    update_interval_climate: 5 
    force_miles: true

notify:
  - platform: command_line
    name: 'Bedroom'
    command: "/config/alexa_wrapper.sh -d 'Bedroom'"
  - platform: command_line
    name: 'Basement'
    command: "/config/alexa_wrapper.sh -d 'Basement'"
  - platform: command_line
    name: 'Kitchen'
    command: "/config/alexa_wrapper.sh -d 'Kitchen Dot'"
  - platform: command_line
    name: 'Office'
    command: "/config/alexa_wrapper.sh -d 'Office'"

weather:
  - platform: darksky
    api_key: !secret darksky_key

zwave:
  network_key: !secret zwave_key
  usb_path: /dev/ttyACM0
