homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 70
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages

mobile_app:

#logger:
#  default: debug

http:
  api_password: !secret http
  base_url: !secret url

lovelace:
  mode: yaml

automation: !include_dir_merge_list automations
cloud: !include cloud.yaml
config:
conversation:
discovery:
  ignore:
    - roku
    - apple_tv
frontend:
  themes: !include themes.yaml
group: !include groups.yaml
history:

ios:
  push:
    categories:
      - name: arriving
        identifier: 'arriving'
        actions:
          - identifier: 'SET_ARRIVING'
            title: 'Yes'

logbook:
recorder:
  exclude:
    domains:
      - input_number
  db_url: !secret db_url
script: !include scripts.yaml
shopping_list:
sun:
tts:
  - platform: google_translate
    service_name: google_say
updater:

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

climate:
  - platform: venstar
    host: X.X.X.X
    ssl: false
    timeout: 5

lutron_caseta_pro:
    bridges:
      - host: X.X.X.X
        mac: 
        switch: [ 8, 9, 10, 12, 18 ]
        cover: [ 23, 24 ]

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com

tplink:
  discovery: false
  switch:
    - host: X.X.X.X
    - host: X.X.X.X
#    - host: X.X.X.X
#    - host: X.X.X.X
#    - host: X.X.X.X
    - host: X.X.X.X
    - host: X.X.X.X

camera:
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=BOX
    name: Radar

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

  - platform: season

  - platform: uptime
    unit_of_measurement: minutes
  - platform: template
    sensors:
      leaf_charge_time:
        entity_id: sensor.leaf_charge
        friendly_name: "LEAF Charge Time (6.6 kW)"
        value_template: "{{(0.40 * (100-states('sensor.leaf_charge')|int)/6.6) | round(2)}}"
        unit_of_measurement: 'Hours'
        icon_template: mdi:timer


scene:
  - name: Dinner
    entities:
      light.dining_room_main_lights:
        state: on
        brightness: 40
      light.kitchen_main_lights:
        state: on
        brightness: 30
      light.living_room_floor_lamp:
        state: off
  - name: Lights Out
    entities:
      group.away_lights:
        state: off
      group.away_switches:
        state: off
  - name: Good Night
    entities:
      input_boolean.good_night:
        state: on
  - name: Upstairs Off
    entities:
      group.upstairs:
        state: off

nissan_leaf:
    username: "X@EXAMPLE.COM"
    password: !secret nissan_password
    region: NNA
    nissan_connect: true
    update_interval:
      minutes: 30
    update_interval_charging:
      minutes: 15
    update_interval_climate:
      minutes: 5
    force_miles: true

notify:
  - platform: alexa_media
    name: alexa

weblink:
  entities:
    - name: Click Here
      url: /lovelace/0
      icon: mdi:web

binary_sensor:
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]

zwave:
  network_key: !secret zwave_key
  usb_path: /dev/ttyACM0
