light.hue_go_1:
  name: Hue Go
sensor.powerwall_battery:
  icon: mdi:battery
sensor.grid_power:
  icon: mdi:grid
sensor.lifetime_generation:
  icon: mdi:sigma
sensor.connected_optimizers:
  icon: mdi:square
sensor.powerwall_power:
  icon: mdi:battery-charging
sensor.solar_power:
  icon: mdi:weather-sunny
sensor.home_power:
  icon: mdi:home
sensor.season:
  icon: mdi:beach
sensor.dark_sky_summary:
  friendly_name: Current Weather
sensor.solar_month:
  icon: mdi:calendar-blank
sensor.solar_today:
  icon: mdi:calendar-today
sensor.solar_live:
  icon: mdi:flash
sensor.speedtest_ping:
  friendly_name: Ping
  icon: mdi:pulse
sensor.speedtest_download:
  friendly_name: Download
  icon: mdi:arrow-down-bold
sensor.speedtest_upload:
  friendly_name: Upload
  icon: mdi:arrow-up-bold
switch.new_york:
  icon: mdi:city
switch.air_filter:
  icon: mdi:filter
binary_sensor.hallway_thermostat_has_leaf:
  hidden: true
binary_sensor.hallway_thermostat_fan:
  hidden: true
binary_sensor.home_away:
  hidden: true
binary_sensor.hallway_thermostat_online:
  hidden: true
sensor.basement_nest_protect_battery_health:
  friendly_name: 'Nest Battery : Basement'
  icon: mdi:battery
light.br1:
  hidden: true
light.br2:
  hidden: true
light.br3:
  hidden: true
light.dining_room_main_lights:
  friendly_name: Dining Room
light.hallway_main_lights:
  friendly_name: Hallway
light.kitchen_main_lights:
  friendly_name: Kitchen
light.basement:
  hidden: true
sensor.basement_nest_protect_co_status:
  hidden: true
binary_sensor.basement_nest_protect_online:
  hidden: true
sensor.basement_nest_protect_smoke_status:
  hidden: true
sensor.hallway_nest_protect_battery_health:
  friendly_name: 'Nest Battery : Hallway'
  icon: mdi:battery
sensor.hallway_nest_protect_co_status:
  hidden: true
binary_sensor.hallway_nest_protect_online:
  hidden: true
sensor.hallway_nest_protect_smoke_status:
  hidden: true
binary_sensor.hallway_thermostat_is_locked:
  hidden: true
binary_sensor.hallway_thermostat_is_using_emergency_heat:
  hidden: true
sensor.master_bedroom_nest_protect_battery_health:
  friendly_name: 'Nest Battery : Master Bedroom'
  icon: mdi:battery
sensor.master_bedroom_nest_protect_co_status:
  hidden: true
binary_sensor.master_bedroom_nest_protect_online:
  hidden: true
sensor.master_bedroom_nest_protect_smoke_status:
  hidden: true
sensor.hallway_thermostat_target:
  hidden: true
sensor.hallway_thermostat_temperature:
  hidden: true
sensor.yr_symbol:
  friendly_name: Weather
sensor.basement_nest_protect_color_status:
  icon: mdi:fire
  friendly_name: Basement - Nest Protect
sensor.hallway_nest_protect_color_status:
  icon: mdi:fire
  friendly_name: Hallway - Nest Protect
sensor.master_bedroom_nest_protect_color_status:
  icon: mdi:fire
  friendly_name: Bedroom - Nest Protect
sensor.hallway_thermostat_operation_mode:
  hidden: true
sensor.hallway_thermostat_hvac_state:
  friendly_name: HVAC
  icon: mdi:fan
sensor.home_eta:
  hidden: true
light.office_floor_lamp:
  friendly_name: Office
switch.sunroom_main_lights:
  friendly_name: Sunroom
  icon: mdi:lightbulb
light.sunroom_star:
  friendly_name: Sunroom Star
  icon: mdi:star
switch.back_entry_sconces:
  friendly_name: Side Entry Light
  icon: mdi:lightbulb
light.living_room_floor_lamp:
  friendly_name: Living Room
switch.rear_deck_deck_lights:
  friendly_name: Rear Deck
  icon: mdi:lightbulb
switch.front_porch_overhead_light:
  friendly_name: Side Deck
  icon: mdi:lightbulb
sensor.hallway_thermostat_humidity:
  friendly_name: Hallway Humidity
sensor.solaredge_live:
  icon: mdi:weather-sunny
sensor.solaredge_today:
  icon: mdi:calendar-today
lock.assa_abloy_unknown_type0004_idaa00_locked:
  friendly_name: Front Door
lock.assa_abloy_unknown_type0004_idaa00_locked_3:
  friendly_name: Basement Door
lock.schlage_be469_touchscreen_deadbolt_locked:
  friendly_name: Side Door
switch.sunroom_heater:
  icon: mdi:radiator
switch.main_bathroom_exhaust_fan:
  icon: mdi:fan
  friendly_name: Exhaust Fan
light.main_bathroom_vanity_lights:
  friendly_name: Bathroom
  brightness_pct: 50
sensor.zooz_zse40_4in1_sensor_temperature_2:
  friendly_name: Bathroom Temperature
  icon: mdi:temperature-fahrenheit
sensor.zooz_zse40_4in1_sensor_relative_humidity_2:
  friendly_name: Bathroom Humidity
  icon: mdi:water-percent
sensor.zooz_zse40_4in1_sensor_relative_humidity_3:
  friendly_name: Kitchen Humidity
  icon: mdi:water-percent
sensor.zooz_zse40_4in1_sensor_luminance_3:
  friendly_name: Kitchen Luminance
  icon: mdi:candle
sensor.zooz_zse40_4in1_sensor_temperature_3:
  friendly_name: Kitchen Temperature
  icon: mdi:temperature-fahrenheit
binary_sensor.bathroom_motion:
  friendly_name: Bathroom Motion
  icon: mdi:run
binary_sensor.shower_on:
  friendly_name: Shower
  icon: mdi:shower-head
scene.dinner:
  icon: mdi:silverware-fork-knife
scene.lights_out:
  icon: mdi:power
binary_sensor.bathroom_occupied:
  friendly_name: Bathroom Occupied
