- device_tracker.stephensiphone
- device_tracker.iphone
- device_tracker.luis_iphone
- device_tracker.dad_iphone
- device_tracker.aobama
- device_tracker.ajsiphone
- device_tracker.iphone2
- device_tracker.susana
