title: Franklin Pines 
resources:
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/monster-card.js
    type: js
  - url: /local/toggle-lock-entity-row.js
    type: js
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js?v=1
    type: module
  - url: /local/lovelace-fold-entity-row/fold-entity-row.js
    type: js
views:
  - icon: mdi:home
    theme: midnight
    cards:
      - type: entity-filter
        show_empty: false
        entities:
          - input_boolean.take_out_trash 
        state_filter: 
          - on
        card:
          type: entities

      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - sensor.side_door_lock
              - sensor.front_door_lock
              - sensor.basement_door_lock
              - binary_sensor.doorbell_front
              - binary_sensor.doorbell_side
          - type: entity-filter
            show_empty: false
            entities:
              - input_boolean.is_away
              - input_boolean.night_mode
            state_filter:
              - on
            card:
              type: glance
              show_state: false
          - type: entity-filter
            show_empty: false
            entities:
              - device_tracker.stephensiphone
              - device_tracker.iphone
              - device_tracker.luis_iphone
              - device_tracker.dad_iphone
              - device_tracker.aobama
              - device_tracker.ajsiphone
              - device_tracker.iphone2
              - device_tracker.susana
            state_filter: 
              - home
            card:
              type: glance
          - type: custom:thermostat-card
            entity: climate.hallway
            step: 1
            hvac:
              states:
                'off': 'off'
                'cooling': 'cool'
                'heating': 'heat'
              sensor:
                sensor: sensor.hallway_thermostat_hvac_state
          - type: entities
            entities:
              - climate.hallway
              - input_number.day_temperature
              - input_number.night_temperature
      - type: vertical-stack
        cards: 
          - type: glance
            entities:
             - binary_sensor.grid_status
             - sensor.powerwall_battery
             - sensor.home_power
             - sensor.solar_live
          - type: weather-forecast
            entity: weather.dark_sky
          - type: picture-entity
            title: Radar 
            entity: camera.radar 
            camera_image: camera.radar 
            show_state: false
            show_name: false
            tap_action: dialog
            
  - title: Rooms
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            show_state: false
            entities:
              - entity: scene.dinner
                tap_action: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.dinner
              - entity: scene.lights_out
                tap_action: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.lights_out
          - type: entities
            title: Kitchen & Dining Room
            show_header_toggle: false
            entities:
              - lock.schlage_be469_touchscreen_deadbolt_locked
              - entity: light.kitchen_main_lights
                type: custom:slider-entity-row
              - entity: light.dining_room_main_lights
                type: custom:slider-entity-row
              - type: custom:fold-entity-row
                head: sensor.zooz_zse40_4in1_sensor_temperature_3
                items:
                  - binary_sensor.kitchen_motion
                  - sensor.zooz_zse40_4in1_sensor_relative_humidity_3
                  - sensor.zooz_zse40_4in1_sensor_luminance_3
          - type: entities
            title: Living Room
            entities:
              - lock.assa_abloy_unknown_type0004_idaa00_locked
              - entity: light.living_room_floor_lamp
                type: custom:slider-entity-row
              - entity: light.hue_go_1
                type: custom:slider-entity-row
          - type: entities
            title: Basement
            show_header_toggle: false
            entities:
              - lock.assa_abloy_unknown_type0004_idaa00_locked_3
              - input_boolean.basement_tv
              - entity: light.stairs
                type: custom:slider-entity-row
              - entity: light.la_luna
                type: custom:slider-entity-row
      - type: vertical-stack
        cards:
          - type: entities
            title: Hallway
            entities:
              - entity: light.hallway_main_lights
                type: custom:slider-entity-row
          - type: entities
            show_header_toggle: false
            title: Bathroom
            entities:
              - entity: light.main_bathroom_vanity_lights
                type: custom:slider-entity-row
              - switch.main_bathroom_exhaust_fan
              - type: custom:fold-entity-row
                head: binary_sensor.bathroom_occupied
                items:
                  - binary_sensor.bathroom_motion
                  - binary_sensor.shower_on
                  - sensor.zooz_zse40_4in1_sensor_relative_humidity_2
                  - sensor.zooz_zse40_4in1_sensor_temperature_2
          - type: entities
            title: Bedroom
            entities:
              - entity: light.bedroom
                type: custom:slider-entity-row
              - switch.new_york
              - switch.air_filter
      - type: vertical-stack
        cards:
          - type: entities
            title: Sunroom
            entities:
              - switch.sunroom_main_lights
              - entity: light.sunroom_star
                type: custom:slider-entity-row
              - entity: light.sunroom_lamp
                type: custom:slider-entity-row
              - type: custom:toggle-lock-entity-row
                entity: switch.sunroom_heater
          - type: entities
            title: Exterior
            entities:
              - switch.back_entry_sconces
              - switch.rear_deck_deck_lights
              - switch.front_porch_overhead_light
              - light.front_door_light
      - type: entities
        title: Office
        entities:
          - entity: light.office_floor_lamp
            type: custom:slider-entity-row
  - title: Security
    cards:
      - type: custom:monster-card
        card:
          type: glance
          title: Motion
        filter:
          include:
            - entity_id: binary_sensor.*_motion
      - type: glance
        title: Safety 
        entities:
          - sensor.hallway_nest_protect_color_status
          - sensor.master_bedroom_nest_protect_color_status
          - sensor.basement_nest_protect_color_status
          - binary_sensor.basement_water_heater_sensor
      - type: glance
        title: Doors
        entities:
          - sensor.front_door_lock
          - sensor.side_door_lock
          - sensor.basement_door_lock
          - binary_sensor.doorbell_front
          - binary_sensor.doorbell_side
      - type: picture-entity
        title: Front 
        entity: camera.front
        camera_image: camera.front
        show_state: false
      - type: picture-entity
        title: Rear 
        entity: camera.rear 
        camera_image: camera.rear 
        show_state: false
  - title: Energy
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: binary_sensor.grid_status
                name: Electrical Grid
          - type: gauge
            title: Powerwall
            entity: sensor.powerwall_battery
          - type: sensor
            entity: sensor.powerwall_power
            line_color: green
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.home_power
                line_color: teal
              - type: sensor
                entity: sensor.home_energy_consumption
                name: Home Usage
                graph: none
          - type: sensor
            entity: sensor.solar_power
            line_color: yellow
          - type: sensor
            entity: sensor.grid_power
            line_color: grey
          - type: glance
            title: UPS
            entities:
              - sensor.ups_status
              - sensor.ups_battery
              - sensor.ups_input_voltage
              - sensor.ups_load
              - sensor.ups_time_left
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.leaf_charge
                graph: none
              - type: sensor
                entity: sensor.leaf_range
                graph: none
              - type: sensor
                name: Range (AC)
                graph: none
                entity: sensor.leaf_range_ac
          - type: picture-glance
            title: Leaf
            show_header_toggle: false
            entities:
              - binary_sensor.leaf_plug_status
              - switch.leaf_charging_status
              - switch.leaf_climate_control
            image: /local/leaf.jpg
          - type: entities
            title: Sun 
            entities:
              - sun.sun
              - sensor.sunrise
              - sensor.sunset
              - sensor.season
      - type: entities
        title: Solar
        entities:
          - sensor.lifetime_generation
          - sensor.connected_optimizers
          - sensor.solar_max
          - sensor.solar_today
          - sensor.solar_month
  - title: Advanced
    cards:
      - type: entities
        title: Misc
        show_header_toggle: false
        entities:
          - input_boolean.is_away
          - input_boolean.guest_mode
          - input_boolean.night_mode
      - type: entities
        title: Batteries
        entities:
          - sensor.front_door_lock_battery
          - sensor.front_doorbell_battery
          - sensor.side_door_lock_battery
          - sensor.side_doorbell_battery
          - sensor.basement_door_lock_battery
          - sensor.basement_nest_protect_battery_health
          - sensor.hallway_nest_protect_battery_health
          - sensor.master_bedroom_nest_protect_battery_health
          - sensor.kitchen_zooz_battery
          - sensor.bathroom_zooz_battery
          - sensor.basement_water_sensor_battery
      - type: custom:monster-card
        card:
          type: entities
          title: Automations
        filter:
          include:
            - domain: automation

